const actionTypes = {
  ACCEPT_FRIENDSHIP_INVITATION_TYPE: "ACCEPT_FRIENDSHIP_INVITATION_TYPE",
  DECLINE_FRIENDSHIP_INVITATION_TYPE: "ACCEPT_FRIENDSHIP_INVITATION_TYPE",
  POST_SCREAM: "POST_SCREAM",
};

export default actionTypes;
