const actionTypes = {
  LOGGED_IN: "LOGGED_IN",
  ACCEPT_FRIENDSHIP_INVITATION_TYPE: "ACCEPT_FRIENDSHIP_INVITATION_TYPE",
  FILTER_INVITATION_LIST: "FILTER_INVITATION_LIST",
  POST_SCREAM: "POST_SCREAM",
  POST_STORY: "POST_STORY",
};

export default actionTypes;
