const actionTypes = {
  ACCEPT_FRIENDSHIP_INVITATION: "ACCEPT_FRIENDSHIP_INVITATION",
  DECLINE_FRIENDSHIP_INVITATION: "DECLINE_FRIENDSHIP_INVITATION",
  POST_SCREAM: "POST_SCREAM",
};

export default actionTypes;
